/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller
import taller.Irrigation._

object App {
  def main(args: Array[String]): Unit = {
    val n = 3  // Numero de Tablones
    val finca: Finca = fincaAlAzar(n)

    println("Finca generada:")
    println(f"Id  ts  tr  p") 
    finca.zipWithIndex.foreach { case ((ts, tr, p), i) =>
      println(f"$i%3d  $ts%3d  $tr%3d  $p%3d")
    }

    // Generar matriz de distancias aleatoria 
    val distancia: Distancia = distanciaAlAzar(n)

    println("\nMatriz de distancias:")
    distancia.foreach { fila =>
      println(fila.map(d => f"$d%3d").mkString(" "))
    }

    //  Calcular programacion de riego optima (min(CostoTotal))
    val (progOpt, costoOpt) = ProgramacionRiegoOptimo(finca, distancia)

    //  Calcular costos parciales 
    val costoRiego = costoRiegoFinca(finca, progOpt)
    val costoMov = costoMovilidad(finca, progOpt, distancia)
    val costoTotal = costoRiego + costoMov

    // Mostrar resultados 
    println("\nProgramacion de riego optima (turnos de cada tablon):")
    progOpt.zipWithIndex.foreach { case (turno, i) =>
      println(f"Tablon $i -> Turno: $turno")
    }

    println(f"\nCosto riego: $costoRiego")
    println(f"Costo movilidad: $costoMov")
    println(f"Costo total: $costoTotal")


}
  def greeting(): String = "Hello, world!"
  }
